apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aco-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-aco-gateway
                port:
                  number: 7070
