// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	UnaryRequest(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	ClientStreamRequest(ctx context.Context, opts ...grpc.CallOption) (ChatService_ClientStreamRequestClient, error)
	ServerStreamRequest(ctx context.Context, in *Message, opts ...grpc.CallOption) (ChatService_ServerStreamRequestClient, error)
	BidiStreamRequest(ctx context.Context, opts ...grpc.CallOption) (ChatService_BidiStreamRequestClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) UnaryRequest(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.ChatService/UnaryRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ClientStreamRequest(ctx context.Context, opts ...grpc.CallOption) (ChatService_ClientStreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], "/chat.ChatService/ClientStreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceClientStreamRequestClient{stream}
	return x, nil
}

type ChatService_ClientStreamRequestClient interface {
	Send(*Message) error
	CloseAndRecv() (*Message, error)
	grpc.ClientStream
}

type chatServiceClientStreamRequestClient struct {
	grpc.ClientStream
}

func (x *chatServiceClientStreamRequestClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceClientStreamRequestClient) CloseAndRecv() (*Message, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) ServerStreamRequest(ctx context.Context, in *Message, opts ...grpc.CallOption) (ChatService_ServerStreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], "/chat.ChatService/ServerStreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceServerStreamRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_ServerStreamRequestClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatServiceServerStreamRequestClient struct {
	grpc.ClientStream
}

func (x *chatServiceServerStreamRequestClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) BidiStreamRequest(ctx context.Context, opts ...grpc.CallOption) (ChatService_BidiStreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[2], "/chat.ChatService/BidiStreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceBidiStreamRequestClient{stream}
	return x, nil
}

type ChatService_BidiStreamRequestClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatServiceBidiStreamRequestClient struct {
	grpc.ClientStream
}

func (x *chatServiceBidiStreamRequestClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceBidiStreamRequestClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	UnaryRequest(context.Context, *Message) (*Message, error)
	ClientStreamRequest(ChatService_ClientStreamRequestServer) error
	ServerStreamRequest(*Message, ChatService_ServerStreamRequestServer) error
	BidiStreamRequest(ChatService_BidiStreamRequestServer) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) UnaryRequest(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryRequest not implemented")
}
func (UnimplementedChatServiceServer) ClientStreamRequest(ChatService_ClientStreamRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamRequest not implemented")
}
func (UnimplementedChatServiceServer) ServerStreamRequest(*Message, ChatService_ServerStreamRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamRequest not implemented")
}
func (UnimplementedChatServiceServer) BidiStreamRequest(ChatService_BidiStreamRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method BidiStreamRequest not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_UnaryRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UnaryRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/UnaryRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UnaryRequest(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ClientStreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).ClientStreamRequest(&chatServiceClientStreamRequestServer{stream})
}

type ChatService_ClientStreamRequestServer interface {
	SendAndClose(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatServiceClientStreamRequestServer struct {
	grpc.ServerStream
}

func (x *chatServiceClientStreamRequestServer) SendAndClose(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceClientStreamRequestServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatService_ServerStreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Message)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).ServerStreamRequest(m, &chatServiceServerStreamRequestServer{stream})
}

type ChatService_ServerStreamRequestServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type chatServiceServerStreamRequestServer struct {
	grpc.ServerStream
}

func (x *chatServiceServerStreamRequestServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_BidiStreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).BidiStreamRequest(&chatServiceBidiStreamRequestServer{stream})
}

type ChatService_BidiStreamRequestServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatServiceBidiStreamRequestServer struct {
	grpc.ServerStream
}

func (x *chatServiceBidiStreamRequestServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceBidiStreamRequestServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryRequest",
			Handler:    _ChatService_UnaryRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreamRequest",
			Handler:       _ChatService_ClientStreamRequest_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamRequest",
			Handler:       _ChatService_ServerStreamRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStreamRequest",
			Handler:       _ChatService_BidiStreamRequest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
