apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: target-namespace
  source:
    repoURL: https://username:password@gitea.net/aco/tester.git
    targetRevision: HEAD 
    path: deploy/overlay/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
