version: "3"
services:

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: flu-3-elastic
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.17.0
    container_name: flu-3-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  fluentd:
    container_name: flu-3-http-request
    user: root
    build:
      context: .
    volumes:
      - ./output:/output
      - ./config:/fluentd/etc
    logging:
      driver: "local"
    ports:
      - 9880:9880
