apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.app.svcPort }}
    targetPort: {{ .Values.app.podPort }}

    