version: "3.9"
services:
  cassandra1:
    image: cassandra:latest
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./apps/cassandra1_data:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster

  cassandra2:
    image: cassandra:latest
    ports:
      - 7001:7000
      - 9043:9042
    volumes:
      - ./apps/cassandra2_data:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster

  cassandra3:
    image: cassandra:latest
    depends_on:
      - cassandra1
      - cassandra2
    ports:
      - 7002:7000
      - 9044:9042
    volumes:
      - ./apps/cassandra3_data:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster

