apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-prometheus
  namespace: linkerd-viz
spec:
  secretName: secret-cert-prometheus
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - PPWI
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames: [prometheus.milkcargo.cn]
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod-prometheus
