appInitial: spa
stage: dev

app:
  mongo:
    storageClass: standard
    storage: 1Gi
    devNeedNodePort: false
    devNodePortSvcPort: 32100
    backupCron: "* * 30 2 *"
  elastic:
    storageClass: standard
    plugZip:
      analysisIk: https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.16.3/elasticsearch-analysis-ik-7.16.3.zip
      analysisPinyin: https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v7.16.3/elasticsearch-analysis-pinyin-7.16.3.zip
      analysisStconvert: https://github.com/medcl/elasticsearch-analysis-stconvert/releases/download/v7.16.3/elasticsearch-analysis-stconvert-7.16.3.zip
    data:
      storage: 1Gi
    plugin:
      storage: 1Gi
    pluginIk:
      storage: 200Mi
