apiVersion: v1
kind: Service
metadata:
  name: service-for-{{ .Values.app.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.label }}
  ports:
  - port: {{ .Values.spec.servicePort | default 8080 }}
    targetPort: 3000