apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
spec:
  service:
    ports:
      - port: 11000
        targetPort: 12000  # the pod opened port number
  webhook:
    this-should-be-the-event-name:
      port: "12000"        # the pod opened port number
      endpoint: /endpoint
      method: GET
