kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1               # point the HPA at the sample application you created above
    kind: Deployment
    name: sample-app
  minReplicas: 1                      # autoscale between 1 and 10 replicas
  maxReplicas: 10
  metrics:
    - type: Pods                      # use a "Pods" metric, which takes the average of the given metric,
      pods:                           # across all pods controlled by the autoscaling target
        metric:
          name: http_requests_total   # use the metric that you used above: /pod/metrics
        target:                       # target 500 milli-requests per second, which is 1 request every two seconds
          type: Value
          averageValue: 500m
